name: nutriclock_app
description: An application to help monitorize nutritional plans

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  shared_preferences: ^0.5.6+1
  splashscreen: 1.2.0
  image_picker: ^0.7.0
  intl: 0.17.0
  flutter_launcher_icons: ^0.9.0
  flutter_typeahead: ^1.8.8
  percent_indicator: ^2.1.8
  syncfusion_flutter_datepicker: ^18.3.50-beta
  multiselect_formfield: ^0.1.5
  syncfusion_flutter_charts: ^18.3.52
  loading: ^1.0.2
  badges: ^1.1.6
  web_socket_channel: ^1.1.0
  syncfusion_localizations: ^18.1.36
  bubble: ^1.2.1
  firebase_messaging: ^9.1.1
  plugin_platform_interface: ^2.0.0
  firebase_core: ^1.0.3
  url_launcher: ^6.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/bg_login.png
    - assets/images/nutri.png
    - assets/images/logo.png
    - assets/images/logo_horizontal.png
    - assets/images/bg_drawer.jpg
    - assets/images/bg_home.jpg
    - assets/images/bg_sleep.jpg
    - assets/sleep/sleep.png
    - assets/sleep/stats.png
    - assets/sleep/tip.png
    - assets/images/bg_chat.png
    - assets/images/bg_sport_detail.jpg
    - assets/images/bg_profile.png
    - assets/images/bg_disease.png
    - assets/images/bg_medication.png
    - assets/images/sport_woman.png
    - assets/images/sport_man.png
    - assets/images/email.png
    - assets/images/sleep_man.png
    - assets/images/password.png
    - assets/images/notifications.png
    - assets/images/bg_sport.png
    - assets/images/bg_green_gradient.png
    - assets/images/bg_green.png
    - assets/images/likert1.png
    - assets/images/likert2.png
    - assets/images/likert3.png
    - assets/images/likert4.png
    - assets/images/likert5.png
    - assets/images/likert1_selected.png
    - assets/images/likert2_selected.png
    - assets/images/likert3_selected.png
    - assets/images/likert4_selected.png
    - assets/images/likert5_selected.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Neucha
      fonts:
        - asset: fonts/Neucha-Regular.ttf
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
